[boris]
  version = 1

[build.dist-validate]
  command = [["validate-respect"]]
[build.dist-7-10]

[build.branches-7-10]

[build.all-submodules]
  command = [["dangling-refs"]]
[build.all-rebased]
  command = [["rebased"]]
