[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-ambiata/master-haskell-library-0.0.1-20160114232634-a8a6f45"
  version = 1
  sha1 = "31b3c32d3377b776145ca1c1ab25ccdb05d8cb8d"

[build.dist]
  HADDOCK = "true"

[build.branches]
